// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvnhdusemJdOQuMc992DdllXbRW4TdRPs',
    appId: '1:380562063866:web:e93e44e1354b12c3b86443',
    messagingSenderId: '380562063866',
    projectId: 'todo-5a704',
    authDomain: 'todo-5a704.firebaseapp.com',
    storageBucket: 'todo-5a704.appspot.com',
    measurementId: 'G-HD1D5F88XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJfkVfTeTtPywmg2vEWNWAXa4X9SXHdlU',
    appId: '1:380562063866:android:a0241b4f66c4d190b86443',
    messagingSenderId: '380562063866',
    projectId: 'todo-5a704',
    storageBucket: 'todo-5a704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0n5C8BMWoAlyp1lpV2AqER-CcXWIP5lo',
    appId: '1:380562063866:ios:5c590ed7f01f080eb86443',
    messagingSenderId: '380562063866',
    projectId: 'todo-5a704',
    storageBucket: 'todo-5a704.appspot.com',
    iosBundleId: 'com.todoapp.ent5m',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0n5C8BMWoAlyp1lpV2AqER-CcXWIP5lo',
    appId: '1:380562063866:ios:f36d86c6938f4291b86443',
    messagingSenderId: '380562063866',
    projectId: 'todo-5a704',
    storageBucket: 'todo-5a704.appspot.com',
    iosBundleId: 'com.todoapp.ent5m.RunnerTests',
  );
}
